sync and repo now push to implicit subdirs of the target

diff --git a/sync.commands/push b/sync.commands/push
--- a/sync.commands/push
+++ b/sync.commands/push
@@ -26,7 +26,7 @@ while [ "$1" ]; do
 done
 
 [ "$target" ] || die "Target was not provided"
-load_target $target $target_args || die "Target could not be loaded: $target $target_args"
+load_target $target "backup" $target_args || die "Target could not be loaded: $target $target_args"
 if [ "$GROUP" ]; then
 	shift
 	for target in $GROUP; do
