Added git-commands

diff --git a/push_repo b/push_repo
--- a/push_repo
+++ b/push_repo
@@ -6,6 +6,8 @@ fi
 source $BACKUP_EXECUTABLE_DIR/library.sh || exit 1
 source $BACKUP_EXECUTABLE_DIR/load-settings.sh || exit 1
 
+source $BACKUP_EXECUTABLE_DIR/git-commands.sh || exit 1
+
 function load_remote_repo {
 	REMOTES="$BACKUP_ROOT/remotes/$REPO_NAME";
 	if [ ! -e "$REMOTES" ]; then
@@ -36,9 +38,9 @@ if [ "$REPO_TYPE" = "local" ]; then
 		REPO_PATH=$REPO_PATH/$PROJECT.git
 	else
 		REPO_PATH=$REPO_PATH/$PROJECT.git
-		git init --bare $REPO_PATH || error "git init failed to create repository at $REPO_PATH";
+		git_init_mirrored "$REPO_PATH" || error "git init failed to create repository at $REPO_PATH";
 	fi
-	git push --mirror $REPO_PATH
+	git_push_to_mirrored "$REPO_PATH"
 elif [ "$REPO_TYPE" = "ssh" ]; then
 	SSH_URL=${1?"URL must be given for $REPO_NAME"};
 	SSH_USERNAME=${2?"username must be given for $REPO_NAME"};
