Failed profile runs now emit errors (and cause the parent process to fail)

diff --git a/profiles/git b/profiles/git
--- a/profiles/git
+++ b/profiles/git
@@ -41,8 +41,8 @@ case "$cmd" in
 		done ;;
 	-public) push_to_git github ;;
 	all) 
-		run_profile git -public
-		run_profile git -private
+		run_profile git -public || error "Failed to push to public repos"
+		run_profile git -private || error "Failed to push to private repos"
 	;;
 	*) push_to_git $1 ;;
 esac
